### ISSUE TITLE
react-native-debugger not connected

### ISSUE THREAD

**Issue by Yasir5247** [kanzitelli/rnn-starter#63]
I was trying to connect react-native-debugger but the app goes blank without any errors from the console.

**Comment by rizwanatta** [comment]
can you elaborate a little more what you have tried to solve the issue! any reproduceable steps @Yasir5247

**Comment by Yasir5247** [comment]
i guess its not possible to run react-native-debugger if re-animated library is installed. have to use flipper

**Comment by pruge** [comment]
I installed it by running:
> npx cli-rn new app -t rnn

It works fine.

However, when entering debug mode, the app is forcibly terminated and no error message is displayed.

Here is the part caught by adb logcat.

> adb -d logcat com.app:D *




```bash
12-31 03:08:31.503  6460  6499 D SoLoader: About to load: libturbomodulejsijni.so
12-31 03:08:31.504  6460  6499 D SoLoader: libturbomodulejsijni.so not found on /data/data/clirn.app/lib-main
12-31 03:08:31.504  6460  6499 D SoLoader: libturbomodulejsijni.so found on /data/app/clirn.app-02xFQ8-Dmn03Ryx87Ox4QA==/lib/arm64
12-31 03:08:31.504  6460  6499 D SoLoader: Not resolving dependencies for libturbomodulejsijni.so
12-31 03:08:31.506  6460  6499 D SoLoader: Loaded: libturbomodulejsijni.so
12-31 03:08:31.510  6460  6499 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 6499 (create_react_co), pid 6460 (clirn.app)
12-31 03:08:31.565  6514  6514 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
12-31 03:08:31.565  1356  1356 I /system/bin/tombstoned: received crash request for pid 6499
12-31 03:08:31.566  6514  6514 I crash_dump64: performing dump of process 6460 (target tid = 6499)
12-31 03:08:31.575  6514  6514 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-31 03:08:31.575  6514  6514 F DEBUG   : Build fingerprint: 'xiaomi/lavender/lavender:10/QKQ1.190910.002/V12.5.1.0.QFGMIXM:user/release-keys'
12-31 03:08:31.575  6514  6514 F DEBUG   : Revision: '0'
12-31 03:08:31.575  6514  6514 F DEBUG   : ABI: 'arm64'
12-31 03:08:31.576  6514  6514 F DEBUG   : Timestamp: 2021-12-31 03:08:31+0900
12-31 03:08:31.576  6514  6514 F DEBUG   : pid: 6460, tid: 6499, name: create_react_co  >>> clirn.app <<<
12-31 03:08:31.576  6514  6514 F DEBUG   : uid: 10728
12-31 03:08:31.576  6514  6514 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
12-31 03:08:31.576  6514  6514 F DEBUG   : Cause: null pointer dereference
12-31 03:08:31.576  6514  6514 F DEBUG   :     x0  0000007d684cdfe8  x1  0000000000000000  x2  0000007d684cdee0  x3  0000007dd525e598
12-31 03:08:31.576  6514  6514 F DEBUG   :     x4  0000007d684cdcd8  x5  0000007dc9c26172  x6  0000000000000002  x7  0000007d684cdbb8
12-31 03:08:31.576  6514  6514 F DEBUG   :     x8  0000007dc9464d60  x9  0000000000000000  x10 0000000000000000  x11 0000000000000001
12-31 03:08:31.576  6514  6514 F DEBUG   :     x12 0000000000000000  x13 0000000000000000  x14 0000000000000012  x15 00000000000000ff
12-31 03:08:31.576  6514  6514 F DEBUG   :     x16 0000007d58379c38  x17 0000007d58306350  x18 0000007d5f10c000  x19 0000007dc4b13c00
12-31 03:08:31.576  6514  6514 F DEBUG   :     x20 0000000000000000  x21 0000007dc4b13c00  x22 0000007d684ce760  x23 0000007dc9c26077
12-31 03:08:31.576  6514  6514 F DEBUG   :     x24 0000000000000004  x25 0000007d684d0020  x26 0000007dc4b13cb0  x27 0000000000000001
12-31 03:08:31.576  6514  6514 F DEBUG   :     x28 0000007d684ce4f0  x29 0000007d684ce3b0
12-31 03:08:31.576  6514  6514 F DEBUG   :     sp  0000007d684cdf20  lr  0000007d582f5960  pc  0000007d582f5968
12-31 03:08:31.620  6460  6509 E AndroidRuntime: FATAL EXCEPTION: mqt_js
12-31 03:08:31.620  6460  6509 E AndroidRuntime: Process: clirn.app, PID: 6460
12-31 03:08:31.620  6460  6509 E AndroidRuntime: java.lang.AssertionError: No source URL loaded, have you initialised the instance?
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:19)
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at com.facebook.react.modules.debug.SourceCodeModule.getTypedExportedConstants(SourceCodeModule.java:39)
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at com.facebook.fbreact.specs.NativeSourceCodeSpec.getConstants(NativeSourceCodeSpec.java:38)
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:142)
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
12-31 03:08:31.620  6460  6509 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
12-31 03:08:31.624  1959  6518 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-31 03:08:31.624  1959  1993 W ActivityTaskManager:   Force finishing activity clirn.app/.MainActivity
12-31 03:08:31.626 26609 24627 D Launcher: get showing item successandroid.graphics.Bitmap@fb54d07
12-31 03:08:31.628  1959  1993 D ActivityTrigger: ActivityTrigger activityPauseTrigger
12-31 03:08:31.637  6460  6509 I Process : Sending signal. PID: 6460 SIG: 9
```

**Comment by kanzitelli** [comment]
hey @pruge! Thank you for reporting the issue! The progress also might be found in #64.
There is probably a small issue with setting up RNN. I'll check it out asap! Or maybe @rizwanatta has already solved this? 🙂

**Comment by kanzitelli** [comment]
@pruge so the issue with `react-native-debugger` and `debug` mode is that they can't work together with `react-native-reanimated`. You will need to use Flipper for debugging as @Yasir5247 noted here before. Flipper progress is at #64.
