### ISSUE TITLE
[Non-runtime] Too many issue from ESLint screenings

### ISSUE THREAD

**Issue by phathuynh5519** [kanzitelli/rnn-starter#77]
Folks, The sourcebase has too many issues  from ESLint screenings, please help us resolve the eslint issues, all tsx files get warning issues from the VSCode IDE, 
```
D:\Demos\rnn-starter>npm run lint

> rnn-starter@13.0.0 lint D:\Demos\rnn-starter
> eslint . --ext .js,.jsx,.ts,.tsx


Oops! Something went wrong! :(

ESLint: 8.10.0

TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js': Class extends value undefined is not a constructor or null
Referenced from: D:\Demos\rnn-starter\.eslintrc.js
    at Object.<anonymous> (D:\Demos\rnn-starter\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\CLIEngine.js:12:34)
    at Module._compile (D:\Demos\rnn-starter\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (D:\Demos\rnn-starter\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\Demos\rnn-starter\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\index.js:14:14)   
    at Module._compile (D:\Demos\rnn-starter\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rnn-starter@13.0.0 lint: `eslint . --ext .js,.jsx,.ts,.tsx`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the rnn-starter@13.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Roaming\npm-cache\_logs\2022-02-28T08_01_35_227Z-debug.log
```
![image](https://user-images.githubusercontent.com/59623591/155948445-b488eb2a-2f8b-48c7-a748-ac5b96ab7e46.png)
Thanks A LOT

**Comment by kanzitelli** [comment]
hey @phathuynh5519, thanks for reporting the issue!

Can you check 13.0.1 version please?

**Comment by phathuynh5519** [comment]
> 13.0.1 ve



> 

Bro, what modules do u mean ? 13.0.1 ? latest eslint version is 8.10.x
