### ISSUE TITLE
[Run-time] Too many warnings from "Possible Unhandled Promise Rejection"

### ISSUE THREAD

**Issue by phathuynh5519** [kanzitelli/rnn-starter#79]
Folks, please help investigate the issue abt expo-file-system.downloadAsync, it causes too many warnings, if possible please remove the module from the starter kit, there are other options, lets focus on the core needs,
Cheers,

```
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: The method or property expo-file-system.downloadAsync is not available on android, are you sure you've linked all the native dependencies properly?
Error: The method or property expo-file-system.downloadAsync is not available on android, are you sure you've linked all the native dependencies properly?
    at construct (native)
    at Wrapper (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:23492:64)
    at construct (native)
    at _createSuperInternal (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:212837:322)
    at call (native)
    at CodedError (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:212850:26)
    at construct (native)
    at _createSuperInternal (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:212876:322)
    at call (native)
    at UnavailabilityError (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:212887:25)
    at downloadAsync$ (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:224928:97)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:25001:32)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24903:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24933:19)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:82:14)
    at callInvokeWithMethodAndArg (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24932:33)
    at enqueue (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24937:157)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24952:69)
    at downloadAsync (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:224917:38)
    at _downloadAsyncUnmanagedEnv$ (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:224201:71)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:25001:32)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24903:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24933:19)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:82:14)
    at callInvokeWithMethodAndArg (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24932:33)
    at enqueue (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24937:157)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24952:69)
    at _downloadAsyncUnmanagedEnv (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:224186:38)
    at downloadAsync$ (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:224123:72)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:25001:32)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at call (native)
    ... skipping 85 frames
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24903:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24933:19)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:82:14)
    at callInvokeWithMethodAndArg (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24932:33)
    at enqueue (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24937:157)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24952:69)
    at loadAsync (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:223661:38)
    at componentDidMount$ (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:223483:67)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:25001:32)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24903:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24933:19)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:82:14)
    at callInvokeWithMethodAndArg (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24932:33)
    at enqueue (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24937:157)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24952:69)
    at componentDidMount (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:223471:44)
    at commitLayoutEffectOnFiber (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:18727:51)
    at commitLayoutMountEffects_complete (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:19726:40)
    at commitLayoutEffects_begin (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:19710:46)
    at commitLayoutEffects (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:19694:34)
    at commitRootImpl (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:20964:30)
    at commitRoot (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:20885:25)
    at performSyncWorkOnRoot (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:20498:19)
    at flushSyncCallbacks (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:10792:36)
    at flushSyncCallbacksOnlyInLegacyMode (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:10773:29)
    at scheduleUpdateOnFiber (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:20153:49)
    at updateContainer (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:22547:41)
    at render (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:23123:24)
    at renderApplication (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:84009:78)
    at run (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:83741:64)
    at runApplication (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:83799:28)
    at apply (native)
    at __callFunction (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:6109:36)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:5833:31)
    at __guard (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:6060:15)
    at callFunctionReturnFlushedQueue (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:5832:21)
 WARN  Possible Unhandled Promise Rejection (id: 1):
Error: The method or property expo-file-system.downloadAsync is not available on android, are you sure you've linked all the native dependencies properly?
Error: The method or property expo-file-system.downloadAsync is not available on android, are you sure you've linked all the native dependencies properly?
    at construct (native)
    at Wrapper (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:23492:64)
    at construct (native)
    at _createSuperInternal (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:212837:322)
    at call (native)
    at CodedError (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:212850:26)
    at construct (native)
    at _createSuperInternal (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:212876:322)
    at call (native)
    at UnavailabilityError (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:212887:25)
    at downloadAsync$ (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:224928:97)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:25001:32)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24903:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24933:19)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:82:14)
    at callInvokeWithMethodAndArg (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24932:33)
    at enqueue (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24937:157)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24952:69)
    at downloadAsync (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:224917:38)
    at _downloadAsyncUnmanagedEnv$ (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:224201:71)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:25001:32)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24903:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24933:19)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:82:14)
    at callInvokeWithMethodAndArg (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24932:33)
    at enqueue (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24937:157)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24952:69)
    at _downloadAsyncUnmanagedEnv (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:224186:38)
    at downloadAsync$ (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:224123:72)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:25001:32)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at call (native)
    ... skipping 85 frames
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24903:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24933:19)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:82:14)
    at callInvokeWithMethodAndArg (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24932:33)
    at enqueue (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24937:157)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24952:69)
    at loadAsync (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:223661:38)
    at componentDidMount$ (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:223483:67)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:25001:32)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at call (native)
    at tryCatch (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24831:23)
    at invoke (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24903:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24933:19)
    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/x86/lib/InternalBytecode/InternalBytecode.js:82:14)
    at callInvokeWithMethodAndArg (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24932:33)
    at enqueue (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24937:157)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24873:30)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:24952:69)
    at componentDidMount (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:223471:44)
    at commitLayoutEffectOnFiber (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:18727:51)
    at commitLayoutMountEffects_complete (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:19726:40)
    at commitLayoutEffects_begin (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:19710:46)
    at commitLayoutEffects (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:19694:34)
    at commitRootImpl (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:20964:30)
    at commitRoot (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:20885:25)
    at performSyncWorkOnRoot (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:20498:19)
    at flushSyncCallbacks (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:10792:36)
    at flushSyncCallbacksOnlyInLegacyMode (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:10773:29)
    at scheduleUpdateOnFiber (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:20153:49)
    at updateContainer (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:22547:41)
    at render (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:23123:24)
    at renderApplication (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:84009:78)
    at run (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:83741:64)
    at runApplication (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:83799:28)
    at apply (native)
    at __callFunction (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:6109:36)
    at anonymous (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:5833:31)
    at __guard (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:6060:15)
    at callFunctionReturnFlushedQueue (http://10.0.3.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.rnnstarter&modulesOnly=false&runModule=true:5832:21)
```

**Comment by kanzitelli** [comment]
explanation is here #74
