### ISSUE TITLE
Error "Unable to resolve module"

### ISSUE THREAD

**Issue by ardasatata** [kanzitelli/rnn-starter#95]
<img width="393" alt="Screen Shot 2022-08-31 at 2 57 44 AM" src="https://user-images.githubusercontent.com/17568508/187531394-27648d3f-c624-4508-be14-eea2f6ab432d.png">

## Summary
Hi I'm encountering this issue right after init with `> npx cli-rn new App -t rnn` command
I had to comment on these components to prevent the error
```
// import {Section} from '../components/Section';
// import {BButton} from '../components/Button';
// import {Reanimated2} from '../components/Reanimated2';
// import {Row} from '../components/Row';
```

## Steps to reproduce 

1. `> npx cli-rn new App -t rnn`
2. `yarn start`
3. `yarn ios`

## Metro output

```
error: Error: Unable to resolve module ../components/Section from /Users/ardasatata/dev/krl-app/src/screens/main.tsx: 

None of these files exist:
  * src/components/Section(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * src/components/Section/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  11 | import {useStores} from '../stores';
  12 | import {Props as SampleProps} from './_screen-sample';
> 13 | import {Section} from '../components/Section';
     |                        ^
  14 | import {BButton} from '../components/Button';
  15 | import {Reanimated2} from '../components/Reanimated2';
  16 | import {Row} from '../components/Row';
    at ModuleResolver.resolveDependency (/Users/ardasatata/dev/krl-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/Users/ardasatata/dev/krl-app/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/ardasatata/dev/krl-app/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/ardasatata/dev/krl-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/ardasatata/dev/krl-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/ardasatata/dev/krl-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/ardasatata/dev/krl-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Users/ardasatata/dev/krl-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 1)

```

**Comment by kanzitelli** [comment]
hey @ardasatata! Thanks for reporting the issue.

I have checked and realised that some files under `components` folder are uppercase when they should be lowercase. This somehow happened while updating to RN 0.69.
So what you need to do it to rename all files under `components` folder to lowercase and also change imports to lowercase in files under `screens` folder. Example: `'../components/Section'` must be `'../components/section'`

Or just use `15.0.1` version that is going to be released soon which will be available through `cli-rn` as well.

**Comment by ardasatata** [comment]
Thanks! I'll check it tonight. 🙌🏼
